name: push to public
on:
  push:
    branches: [main]
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.repository == 'Songmu/oss4.fun-private'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - id: generate_token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        repositories: oss4.fun
    - uses: Songmu/action-push-to-another-repository@9a7fe32305f083e5e0984e345f30940d0ff87706 # v2.0.11
      with:
        token: "${{ steps.generate_token.outputs.token }}"
        destination-repository: Songmu/oss4.fun
