name: deploy audio to r2
on:
  push:
    branches:
    - main
    paths:
    - 'audio/**'
  workflow_dispatch:
jobs:
  r2-audio:
    if: github.repository == 'Songmu/oss4.fun'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/r2sync@4eedc394a88b052ed35cb25338f6a47ef9d06baa
      with:
        r2_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        r2_access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        src: ./audio
        dest: r2://oss4.fun/audio
        public_domain: files.oss4.fun
